import { ScheduleSectionType } from "@/components/Schedule/ScheduleSection"

const dayOneSchedule: ScheduleSectionType[] = [
    {
        id: 1,
        slug: 'open',
        name: 'Открытие конгресса',
        start: 1634295900000,
        end: 1634299200000,
        hideEnd: true,
        live: true,
        calendar: false,
        visible: false,
        googleLink: 'https://www.google.com/calendar/event?action=TEMPLATE&dates=20211015T112000Z%2F20211015T120000Z&text=ACD%20%D0%9A%D0%BE%D0%BD%D0%B3%D1%80%D0%B5%D1%81%D1%81.%20%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%20%D0%BA%D0%BE%D0%BD%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B0&location=events.loreal.com.ru&details=',
        iosLink: 'assets/calendar/ev_1.ics',
        record: undefined
    },
    {
        id: 2,
        name: <>СЕКЦИЯ АТОПИЧЕСКИЙ ДЕРМАТИТ:<br />нужна ли коллаборация специалистов?</>,
        slug: 'collab',
        start: 1634299200000,
        end: 1634310000000,
        live: true,
        calendar: true,
        visible: true,
        googleLink: 'https://www.google.com/calendar/event?action=TEMPLATE&dates=20211015T120000Z%2F20211015T150000Z&text=ACD%20%D0%9A%D0%BE%D0%BD%D0%B3%D1%80%D0%B5%D1%81%D1%81.%20%D0%90%D1%82%D0%BE%D0%BF%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9%20%D0%B4%D0%B5%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D1%82%3A%20%D0%BD%D1%83%D0%B6%D0%BD%D0%B0%20%D0%BB%D0%B8%20%D0%BA%D0%BE%D0%BB%D0%BB%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%86%D0%B8%D1%8F%20%D1%81%D0%BF%D0%B5%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D1%81%D1%82%D0%BE%D0%B2%3F&location=events.loreal.com.ru&details=',
        iosLink: 'assets/calendar/ev_2.ics',
        record: undefined,
        events: [
            {
                id: 1,
                name: 'Новик Г.А. о своем докладе',
                author: 'д.м.н., проф., аллерголог-иммунолог',
                preview: 'czy4fNf8DPQ',
                previewImage: 'assets/images/conference/d1p1.png',
                start: null,
                end: null,
            },
            {
                id: 2,
                name: 'Заславский Д.В. о своем докладе',
                author: 'д.м.н., проф., дерматолог',
                preview: 'gA-RjGbYAgA',
                previewImage: 'assets/images/conference/d1p2.png',
                start: null,
                end: null,
            },
            {
                id: 3,
                name: 'Невидимый фронт: роль нормализации микробиома кожи при атопическом дерматите',
                author: 'Аравийская Е.А., д.м.н., проф., дерматолог',
                preview: null,
                start: 1634299200000,
                end: 1634300400000,
                record: 'meTCSUSBhwA',
                previewImage: 'assets/images/schedule/record/15/preview1.png',
            },
            {
                id: 4,
                name: 'Профилактика атопического дерматита у детей: теоретические возможности и практическое воплощение',
                author: 'Заплатников А.Л., д.м.н., проф., педиатр',
                preview: null,
                start: 1634300700000,
                end: 1634301900000,
                record: 'nod2IvwLn5E',
                previewImage: 'assets/images/schedule/record/15/preview2.png',
            },
            {
                id: 5,
                name: 'Атопический дерматит. Искусство побеждать',
                author: 'Новик Г.А., д.м.н., проф., аллерголог-иммунолог',
                preview: null,
                start: 1634302200000,
                end: 1634303400000,
                record: 'Zcoy7-_dz0k',
                previewImage: 'assets/images/schedule/record/15/preview3.png',
            },
            {
                id: 6,
                name: 'Атопический дерматит - маркер аллергического генеза гастроинтестинальных симптомов у детей',
                author: 'Ткаченко М.А., к.м.н., доцент, гастроэнтеролог',
                preview: null,
                start: 1634303700000,
                end: 1634304900000,
                record: 'PSCqpI4FqbA',
                previewImage: 'assets/images/schedule/record/15/preview4.png',
            },
            {
                id: 7,
                name: 'Вопросы топографической дерматологии в детском возрасте',
                author: 'Заславский Д.В., д.м.н., проф., дерматолог',
                preview: null,
                start: 1634305200000,
                end: 1634306400000,
                record: 'uWVpSYtBjH8',
                previewImage: 'assets/images/schedule/record/15/preview5.png',
            },
            {
                id: 8,
                name: 'Атопический дерматит. Следуя обновленным клиническим рекомендациям',
                author: 'Круглова Л.С., д.м.н., проф., дерматолог',
                preview: null,
                start: 1634306700000,
                end: 1634307900000,
                record: 'vFiW0JIsSs8',
                previewImage: 'assets/images/schedule/record/15/preview6.png',
            },
            {
                id: 9,
                name: 'Психосоматика. Мифы и реальность',
                author: <>Клипинина Н.В., клинический психолог</>,
                preview: null,
                start: 1634308200000,
                end: 1634310000000,
                record: 'PrcEvbVoFjI',
                previewImage: 'assets/images/schedule/record/15/preview7.png',
            }
        ]
    }
]

export default dayOneSchedule