import { ScheduleSectionType } from "@/components/Schedule/ScheduleSection"

const dayThreeSchedule: ScheduleSectionType[] = [
    {
        id: 1,
        name: 'СЕКЦИЯ Дерматозы взрослых',
        slug: 'dermatose',
        start: 1634454000000,
        end: 1634459400000,
        live: true,
        calendar: true,
        visible: true,
        googleLink: 'https://www.google.com/calendar/event?action=TEMPLATE&dates=20211017T070000Z%2F20211017T083000Z&text=ACD%20%D0%9A%D0%BE%D0%BD%D0%B3%D1%80%D0%B5%D1%81%D1%81.%20%D0%A1%D0%B5%D0%BA%D1%86%D0%B8%D1%8F%20%D0%94%D0%B5%D1%80%D0%BC%D0%B0%D1%82%D0%BE%D0%B7%D1%8B%20%D0%B2%D0%B7%D1%80%D0%BE%D1%81%D0%BB%D1%8B%D1%85&location=events.loreal.com.ru&details=',
        iosLink: 'assets/calendar/ev_5.ics',
        record: undefined,
        events: [
            {
                id: 1,
                name: 'Проблема акне у взрослых: мнение эксперта',
                author: 'Аравийская Е.А., д.м.н., проф., дерматолог',
                preview: null,
                start: 1634454000000,
                end: 1634455800000,
                record: 'vwXiUbG_tps',
                previewImage: 'assets/images/schedule/record/17/preview1.png',
            },
            {
                id: 2,
                name: 'Ксероз при дерматозах и не только',
                author: 'Соколовский Е.В., д.м.н., проф., дерматолог',
                preview: null,
                start: 1634456100000,
                end: 1634457300000,
                record: '_ArcntTBT30',
                previewImage: 'assets/images/schedule/record/17/preview2.png',
            },
            {
                id: 3,
                name: 'Как можно улучшить качество жизни больных с псориазом?',
                author: 'Хобейш М.М., к.м.н., доц., дерматолог',
                preview: null,
                start: 1634457600000,
                end: 1634458800000,
                record: 'TaSGE-qr36s',
                previewImage: 'assets/images/schedule/record/17/preview3.png',
            },
        ]
    },
    {
        id: 2,
        name: 'ПЕРЕРЫВ',
        slug: 'break3',
        start: 1634459400000,
        end: 1634460300000,
        live: false,
        calendar: false,
        visible: false,
    },
    {
        id: 3,
        name: 'СЕКЦИЯ Онкология для онкологов и не только',
        slug: 'oncology',
        start: 1634460300000,
        end: 1634467500000,
        live: true,
        calendar: true,
        visible: true,
        googleLink: 'https://www.google.com/calendar/event?action=TEMPLATE&dates=20211017T084500Z%2F20211017T104500Z&text=ACD%20%D0%9A%D0%BE%D0%BD%D0%B3%D1%80%D0%B5%D1%81%D1%81.%20%D0%9E%D0%BD%D0%BA%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%8F%20%D0%B4%D0%BB%D1%8F%20%D0%BE%D0%BD%D0%BA%D0%BE%D0%BB%D0%BE%D0%B3%D0%BE%D0%B2%20%D0%B8%20%D0%BD%D0%B5%20%D1%82%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE&location=events.loreal.com.ru&details=',
        iosLink: 'assets/calendar/ev_6.ics',
        record: undefined,
        events: [
            {
                id: 1,
                name: 'Раджабова З.А. о своем докладе',
                author: 'к.м.н., доц., онколог, торакальный хирург, челюстно-лицевой хирург',
                preview: 'Gv79j2T86Ps',
                previewImage: 'assets/images/conference/d3p1.png',
                start: null,
                end: null,
            },
            {
                id: 2,
                name: 'Кожная токсичность при проведении противоопухолевой лекарственной терапии',
                author: 'Ткаченко Е.В., к.м.н., доц., онколог, химиотерапевт',
                preview: null,
                start: 1634460300000,
                end: 1634461500000,
                record: 'AfamFaqVu2Y',
                previewImage: 'assets/images/schedule/record/17/preview4.png',
            },
            {
                id: 3,
                name: 'Лучевой дерматит: механизм возникновения, профилактика и лечение',
                author: 'Михайлов А.В., к.м.н., радиотерапевт',
                preview: null,
                start: 1634461800000,
                end: 1634463000000,
                record: 'p3bKAKcPBXM',
                previewImage: 'assets/images/schedule/record/17/preview5.png',
            },
            {
                id: 4,
                name: 'Как помочь пациенту с кожной токсичностью?',
                author: 'Шливко И.Л., д.м.н., проф., дерматолог',
                preview: null,
                start: 1634463300000,
                end: 1634464500000,
                record: 'WRUxmg7a7wM',
                previewImage: 'assets/images/schedule/record/17/preview6.png',
            },
            {
                id: 5,
                name: 'Особенности ведения онкологических пациентов дерматологом: развенчиваем мифы',
                author: 'Аравийская Е.А., д.м.н., проф., дерматолог',
                preview: null,
                start: 1634464800000,
                end: 1634466000000,
                record: 'VLEuujwqauI',
                previewImage: 'assets/images/schedule/record/17/preview7.png',
            },
            {
                id: 6,
                name: 'Тактика ведения пациентов с меланомой кожи',
                author: 'Раджабова З.А., к.м.н., доц., онколог, торакальный хирург, челюстно-лицевой хирург',
                preview: null,
                start: 1634466300000,
                end: 1634467500000,
                record: 'nqxttg0e5o4',
                previewImage: 'assets/images/schedule/record/17/preview8.png',
            },
        ]
    },
]

export default dayThreeSchedule