import { api } from '@/api'

export const trackerAPI = {
	sendEvent(event: EventsEnum, params = '') {
		return api
			.get(`API?action=send_event&event=${event}${params && `&${params}`}`)
			.then((res) => res.data)
			.catch(console.error)
	},
	sendLike(likeId: LikesEnum) {
		return api
			.get(`API?action=send_like&like_id=${likeId}`)
			.then((res) => res.data)
			.catch(console.error)
	},
}

export enum LikesEnum {
	//green
	greenPopup1Like = 'greenPopup1Like',
	greenPopup2Like = 'greenPopup2Like',
	greenPopup3Like = 'greenPopup3Like',
	greenPopup4Like = 'greenPopup4Like',

	// skinceuticals
	scCeFerulicLike = 'scCeFerulicLike',
	scSilymarinCfLike = 'scSilymarinCfLike',
	scPhytoLike = 'scPhytoLike',

	// lrp
	lrpEffaclarLike = 'lrpEffaclarLike',
	lrpIsoBiomeLike = 'lrpIsoBiomeLike',
	lrpSerumLike = 'lrpSerumLike',
	lrpNiacinamideLike = 'lrpNiacinamideLike',
	lrpLipikarDermLike = 'lrpLipikarDermLike',
	lrpTolerianeLike = 'lrpTolerianeLike',
	lrpBaumeLike = 'lrpBaumeLike',
	lrpCicaplastLike = 'lrpCicaplastLike',
	lrpAntheliosLike = 'lrpAntheliosLike',
	lrpLipikarPedsLike = 'lrpLipikarPedsLike',
	lrpCicaplastPedsLike = 'lrpCicaplastPedsLike',
	lrpLaitLike = 'lrpLaitLike',
	lrpKidsLike = 'lrpKidsLike',
	lrpEffaclarPedsLike = 'lrpEffaclarPedsLike',
	lrpLipikarOncoLike = 'lrpLipikarOncoLike',
	lrpTolerianeOncoLike = 'lrpTolerianeOncoLike',
	lrpAntheliosOncoLike = 'lrpAntheliosOncoLike',
	lrpLaitPedsLike = 'lrpLaitPedsLike',
	lrpKidsPedsLike = 'lrpKidsPedsLike',
	lrpBaumePedsLike = 'lrpBaumePedsLike',
	lrpBaumeOncoLike = 'lrpBaumeOncoLike',

	lrpRosalicLike = 'lrpRosalicLike',
	lrpTolerianeAllergLike = 'lrpTolerianeAllergLike',
	lrpLipikarAllergLike = 'lrpLipikarAllergLike',
	lrpAntheliosAllergLike = 'lrpAntheliosAllergLike',
	lrpLaitAllergLike = 'lrpLaitAllergLike',
	lrpCicaplastAllergLike = 'lrpCicaplastAllergLike',

	// vichy
	vichyLifLike = 'vichyLifLike',
	vichyNeoLike = 'vichyNeoLike',
	vichyMinLike = 'vichyMinLike',
	vichyNormLike = 'vichyNormLike',
	vichyDeodorantLike = 'vichyDeodorantLike',

	// dercos
	dercosPSOLike = 'dercosPSOLike',
	dercosADDLike = 'dercosADDLike',
	dercosAminexilLike = 'dercosAminexilLike',
}

export enum EventsEnum {
	authSuccess = 'authSuccess',
	specSuccess = 'specSuccess',

	mainVisit = 'mainVisit',
	hallVideo = 'hallVideo',
	hallVideoProgress = 'hallVideoProgress',
	mainVisitDuration = 'mainVisitDuration',

	// Conference
	confVisit = 'confVisit',
	confVisitDuration = 'confVisitDuration',
	confCloudVisit = 'confCloudVisit',
	confCloudVisitDuration = 'confCloudVisitDuration',
	confCloudWordEntry = 'confCloudWordEntry',
	confDay1 = 'confDay1',
	confDay2 = 'confDay2',
	confDay3 = 'confDay3',
	confDay4 = 'confDay4',
	confDay5 = 'confDay5',
	confDay6 = 'confDay6',
	confBrochure = 'confBrochure',
	confPhotoVisit = 'confPhotoVisit',

	// Green room
	greenVisit = 'greenVisit',
	greenVisitDuration = 'greenVisitDuration',
	greenGame = 'greenGame',
	greenGameDuration = 'greenGameDuration',
	greenGameResult = 'greenGameResult',
	greenSortVisit = 'greenSortVisit',
	greenSortDuration = 'greenSortDuration',
	greenSortResult = 'greenSortResult',
	greenProductsVisit = 'greenProductsVisit',
	greenMissionVisit = 'greenMissionVisit',
	greenVideo1 = 'greenVideo1',
	greenVideo1Progress = 'greenVideo1Progress',
	greenVideo2 = 'greenVideo2',
	greenVideo2Progress = 'greenVideo2Progress',
	greenVideo3 = 'greenVideo3',
	greenVideo3Progress = 'greenVideo3Progress',
	greenBrochure = 'greenBrochure',
	greenPopup1Visit = 'greenPopup1Visit',
	greenPopup2Visit = 'greenPopup2Visit',
	greenPopup3Visit = 'greenPopup3Visit',
	greenPopup4Visit = 'greenPopup4Visit',
	greenPopup5Visit = 'greenPopup5Visit',
	greenMoreVisit = 'greenMoreVisit',
	greenVichyLabsVisit = 'greenVichyLabsVisit',
	greenLRPLabsVisit = 'greenLRPLabsVisit',
	greenLRPChangesVisit = 'greenLRPChangesVisit',
	greenStory1Visit = 'greenStory1Visit',
	greenStory1Duration = 'greenStory1Duration',
	greenStory2Visit = 'greenStory2Visit',
	greenStory2Duration = 'greenStory2Duration',
	greenStory3Visit = 'greenStory3Visit',
	greenStory3Duration = 'greenStory3Duration',
	greenStory4Visit = 'greenStory4Visit',
	greenStory4Duration = 'greenStory4Duration',
	greenStory5Visit = 'greenStory5Visit',
	greenStory5Duration = 'greenStory5Duration',
	greenStory6Visit = 'greenStory6Visit',
	greenStory6Duration = 'greenStory6Duration',
	greenStory7Visit = 'greenStory7Visit',
	greenStory7Duration = 'greenStory7Duration',
	greenStory8Visit = 'greenStory8Visit',
	greenStory8Duration = 'greenStory8Duration',
	greenStory9Visit = 'greenStory9Visit',
	greenStory9Duration = 'greenStory9Duration',
	greenStory10Visit = 'greenStory10Visit',
	greenStory10Duration = 'greenStory10Duration',
	greenStory11Visit = 'greenStory11Visit',
	greenStory11Duration = 'greenStory11Duration',
	greenStory12Visit = 'greenStory12Visit',
	greenStory12Duration = 'greenStory12Duration',
	greenStory13Visit = 'greenStory13Visit',
	greenStory13Duration = 'greenStory13Duration',
	greenStory14Visit = 'greenStory14Visit',
	greenStory14Duration = 'greenStory14Duration',
	greenStory15Visit = 'greenStory15Visit',
	greenStory15Duration = 'greenStory15Duration',
	greenStory16Visit = 'greenStory16Visit',
	greenStory16Duration = 'greenStory16Duration',
	greenStory17Visit = 'greenStory17Visit',
	greenStory17Duration = 'greenStory17Duration',
	greenStory18Visit = 'greenStory18Visit',
	greenStory18Duration = 'greenStory18Duration',
	greenStory19Visit = 'greenStory19Visit',
	greenStory19Duration = 'greenStory19Duration',
	greenStory20Visit = 'greenStory20Visit',
	greenStory20Duration = 'greenStory20Duration',
	greenStory21Visit = 'greenStory21Visit',
	greenStory21Duration = 'greenStory21Duration',
	greenStory22Visit = 'greenStory22Visit',
	greenStory22Duration = 'greenStory22Duration',
	greenStory23Visit = 'greenStory23Visit',
	greenStory23Duration = 'greenStory23Duration',
	greenStory24Visit = 'greenStory24Visit',
	greenStory24Duration = 'greenStory24Duration',
	greenStory25Visit = 'greenStory25Visit',
	greenStory25Duration = 'greenStory25Duration',
	greenStory26Visit = 'greenStory26Visit',
	greenStory26Duration = 'greenStory26Duration',
	greenStory27Visit = 'greenStory27Visit',
	greenStory27Duration = 'greenStory27Duration',
	greenStory28Visit = 'greenStory28Visit',
	greenStory28Duration = 'greenStory28Duration',
	greenStory29Visit = 'greenStory29Visit',
	greenStory29Duration = 'greenStory29Duration',
	greenStory30Visit = 'greenStory30Visit',
	greenStory30Duration = 'greenStory30Duration',
	greenStory31Visit = 'greenStory31Visit',
	greenStory31Duration = 'greenStory31Duration',
	greenStory32Visit = 'greenStory32Visit',
	greenStory32Duration = 'greenStory32Duration',
	greenStory33Visit = 'greenStory33Visit',
	greenStory33Duration = 'greenStory33Duration',
	greenStory34Visit = 'greenStory34Visit',
	greenStory34Duration = 'greenStory34Duration',

	// Quiz game
	gameVisit = 'gameVisit',
	gamePoints = 'gamePoints',
	gameVisitDuration = 'gameVisitDuration',

	// vichy
	vichyVisit = 'vichyVisit',
	vichyVisitDuration = 'vichyVisitDuration',
	vichyCloudVisit = 'vichyCloudVisit',
	vichyCloudVisitDuration = 'vichyCloudVisitDuration',
	vichyCloudWordEntry = 'vichyCloudWordEntry',
	vichyGame = 'vichyGame',
	vichyGameDuration = 'vichyGameDuration',
	vichyGameVisit = 'vichyGameVisit',
	vichyGameVisitDuration = 'vichyGameVisitDuration',
	vichyGameResult = 'vichyGameResult',
	vichyProductsVisit = 'vichyProductsVisit',
	vichyLifVisit = 'vichyLifVisit',
	vichyDeodorantVisit = 'vichyDeodorantVisit',
	vichyNeoVisit = 'vichyNeoVisit',
	vichyMinVisit = 'vichyMinVisit',
	vichyNormVisit = 'vichyNormVisit',
	vichyVideoVisit = 'vichyVideoVisit',
	vichyVideoProgress = 'vichyVideoProgress',
	vichyMissionVisit = 'vichyMissionVisit',
	vichyBrochure = 'vichyBrochure',
	vichyCatalog = 'vichyCatalog',
	vichyBanner = 'vichyBanner',

	// Dercos
	dercosVisit = 'dercosVisit',
	dercosVisitDuration = 'dercosVisitDuration',
	dercosCloudVisit = 'dercosCloudVisit',
	dercosCloudVisitDuration = 'dercosCloudVisitDuration',
	dercosCloudWordEntry = 'dercosCloudWordEntry',
	dercosGame = 'dercosGame',
	dercosGameDuration = 'dercosGameDuration',
	dercosGameVisit = 'dercosGameVisit',
	dercosGameVisitDuration = 'dercosGameVisitDuration',
	dercosGameResult = 'dercosGameResult',
	dercosProductsVisit = 'dercosProductsVisit',
	dercosMissionVisit = 'dercosMissionVisit',
	dercosTrichologyVisit = 'dercosTrichologyVisit',
	dercosTrichologyProgress = 'dercosTrichologyProgress',
	dercosProjectsVisit = 'dercosProjectsVisit',
	dercosBrochure = 'dercosBrochure',
	dercosPSOVisit = 'dercosPSOVisit',
	dercosADDVisit = 'dercosADDVisit',
	dercosAminexilVisit = 'dercosAminexilVisit',
	dercosBanner = 'dercosBanner',
	dercosCloud = 'dercosCloud',

	// lrp
	lrpVisit = 'lrpVisit',
	lrpVisitDuration = 'lrpVisitDuration',
	lrpCloudVisit = 'lrpCloudVisit',
	lrpCloudVisitDuration = 'lrpCloudVisitDuration',
	lrpCloudWordEntry = 'lrpCloudWordEntry',

	lrpLightbox1 = 'lrpLightbox1',
	lrpLightbox2 = 'lrpLightbox2',
	lrpOncoSupport = 'lrpOncoSupport',
	lrpFondation = 'lrpFondation',
	lrpMelanomaDay = 'lrpMelanomaDay',
	lrpProductsVisit = 'lrpProductsVisit',
	lrpVideoVisit = 'lrpVideoVisit',
	lrpVideoProgress = 'lrpVideoProgress',
	lrpGameVisit = 'lrpGameVisit',
	lrpGameVisitDuration = 'lrpGameVisitDuration',
	lrpGameResult = 'lrpGameResult',

	lrpGame1 = 'lrpGame1',
	lrpGame2 = 'lrpGame2',
	lrpGame3 = 'lrpGame3',
	lrpGame4 = 'lrpGame4',
	lrpGame5 = 'lrpGame5',
	lrpGame6 = 'lrpGame6',
	lrpGame7 = 'lrpGame7',
	lrpGame8 = 'lrpGame8',
	lrpGame9 = 'lrpGame9',
	lrpGame10 = 'lrpGame10',

	moleculeRules = 'moleculeRules',
	moleculeResult = 'moleculeResult',
	// lrp molecules
	lrpMolecule1 = 'lrpMolecule1',
	lrpMolecule2 = 'lrpMolecule2',
	lrpMolecule3 = 'lrpMolecule3',
	lrpMolecule4 = 'lrpMolecule4',
	lrpMolecule5 = 'lrpMolecule5',
	lrpMolecule6 = 'lrpMolecule6',
	lrpMolecule7 = 'lrpMolecule7',
	lrpMolecule8 = 'lrpMolecule8',
	lrpMolecule9 = 'lrpMolecule9',
	lrpMolecule10 = 'lrpMolecule10',
	// vichy molecules
	vichyMolecule1 = 'vichyMolecule1',
	vichyMolecule2 = 'vichyMolecule2',
	vichyMolecule3 = 'vichyMolecule3',
	vichyMolecule4 = 'vichyMolecule4',
	vichyMolecule5 = 'vichyMolecule5',
	vichyMolecule6 = 'vichyMolecule6',
	vichyMolecule7 = 'vichyMolecule7',
	vichyMolecule8 = 'vichyMolecule8',
	vichyMolecule9 = 'vichyMolecule9',
	vichyMolecule10 = 'vichyMolecule10',
	// dercos molecules
	dercosMolecule1 = 'dercosMolecule1',
	dercosMolecule2 = 'dercosMolecule2',
	dercosMolecule3 = 'dercosMolecule3',
	dercosMolecule4 = 'dercosMolecule4',
	dercosMolecule5 = 'dercosMolecule5',
	dercosMolecule6 = 'dercosMolecule6',
	dercosMolecule7 = 'dercosMolecule7',
	dercosMolecule8 = 'dercosMolecule8',
	dercosMolecule9 = 'dercosMolecule9',
	dercosMolecule10 = 'dercosMolecule10',

	lrpEffaclarVisit = 'lrpEffaclarVisit',
	lrpIsoBiomeVisit = 'lrpIsoBiomeVisit',
	lrpSerumVisit = 'lrpSerumVisit',
	lrpNiacinamideVisit = 'lrpNiacinamideVisit',
	lrpLipikarDermVisit = 'lrpLipikarDermVisit',
	lrpLaitVisit = 'lrpLaitVisit',
	lrpRosalicVisit = 'lrpRosalicVisit',
	lrpTolerianeVisit = 'lrpTolerianeVisit',
	lrpBaumeVisit = 'lrpBaumeVisit',
	lrpCicaplastVisit = 'lrpCicaplastVisit',
	lrpAntheliosVisit = 'lrpAntheliosVisit',

	lrpLipikarPedsVisit = 'lrpLipikarPedsVisit',
	lrpCicaplastPedsVisit = 'lrpCicaplastPedsVisit',
	lrpLaitPedsVisit = 'lrpLaitPedsVisit',
	lrpKidsPedsVisit = 'lrpKidsPedsVisit',
	lrpBaumePedsVisit = 'lrpBaumePedsVisit',
	lrpEffaclarPedsVisit = 'lrpEffaclarPedsVisit',

	lrpLipikarOncoVisit = 'lrpLipikarOncoVisit',
	lrpTolerianeOncoVisit = 'lrpTolerianeOncoVisit',
	lrpAntheliosOncoVisit = 'lrpAntheliosOncoVisit',
	lrpBaumeOncoVisit = 'lrpBaumeOncoVisit',

	lrpTolerianeAllergVisit = 'lrpTolerianeAllergVisit',
	lrpLipikarAllergVisit = 'lrpLipikarAllergVisit',
	lrpAntheliosAllergVisit = 'lrpAntheliosAllergVisit',
	lrpLaitAllergVisit = 'lrpLaitAllergVisit',
	lrpCicaplastAllergVisit = 'lrpCicaplastAllergVisit',

	lrpMissionVisit = 'lrpMissionVisit',
	lrpBrochure = 'lrpBrochure',
	lrpScheme = 'lrpScheme',
	lrpPhotoVisit = 'lrpPhotoVisit',

	// conference
	confDay1Video1 = 'confDay1Video1',
	confDay1Video2 = 'confDay1Video2',
	confDay1Video3 = 'confDay1Video3',
	confDay1Video4 = 'confDay1Video4',
	confDay1Video5 = 'confDay1Video5',
	confDay1Video6 = 'confDay1Video6',
	confDay1Video7 = 'confDay1Video7',
	confDay1Video8 = 'confDay1Video8',
	confDay1Video9 = 'confDay1Video9',

	confDay2Video1 = 'confDay2Video1',
	confDay2Video2 = 'confDay2Video2',
	confDay2Video3 = 'confDay2Video3',
	confDay2Video4 = 'confDay2Video4',
	confDay2Video5 = 'confDay2Video5',
	confDay2Video6 = 'confDay2Video6',
	confDay2Video7 = 'confDay2Video7',
	confDay2Video8 = 'confDay2Video8',
	confDay2Video9 = 'confDay2Video9',
	confDay2Video10 = 'confDay2Video10',

	confDay3Video1 = 'confDay3Video1',
	confDay3Video2 = 'confDay3Video2',
	confDay3Video3 = 'confDay3Video3',
	confDay3Video4 = 'confDay3Video4',
	confDay3Video5 = 'confDay3Video5',
	confDay3Video6 = 'confDay3Video6',
	confDay3Video7 = 'confDay3Video7',
	confDay3Video8 = 'confDay3Video8',
	confDay3Video9 = 'confDay3Video9',
	confDay3Video10 = 'confDay3Video10',
	confDay3Video11 = 'confDay3Video11',

	confDay4Video1 = 'confDay4Video1',
	confDay4Video2 = 'confDay4Video2',
	confDay4Video3 = 'confDay4Video3',
	confDay4Video4 = 'confDay4Video4',
	confDay4Video5 = 'confDay4Video5',
	confDay4Video6 = 'confDay4Video6',
	confDay4Video7 = 'confDay4Video7',

	confDay5Video1 = 'confDay5Video1',
	confDay5Video2 = 'confDay5Video2',
	confDay5Video3 = 'confDay5Video3',
	confDay5Video4 = 'confDay5Video4',
	confDay5Video5 = 'confDay5Video5',
	confDay5Video6 = 'confDay5Video6',
	confDay5Video7 = 'confDay5Video7',
	confDay5Video8 = 'confDay5Video8',
	confDay5Video9 = 'confDay5Video9',
	confDay5Video10 = 'confDay5Video10',
	confDay5Video11 = 'confDay5Video11',
	confDay5Video12 = 'confDay5Video12',

	confDay6Video1 = 'confDay6Video1',
	confDay6Video2 = 'confDay6Video2',
	confDay6Video3 = 'confDay6Video3',
	confDay6Video4 = 'confDay6Video4',
	confDay6Video5 = 'confDay6Video5',
	confDay6Video6 = 'confDay6Video6',
	confDay6Video7 = 'confDay6Video7',
	confDay6Video8 = 'confDay6Video8',
	confDay6Video9 = 'confDay6Video9',
	confDay6Video10 = 'confDay6Video10',

	// ----------------- UNUSED OLD -----------------
	acdPhotoDownload = 'acdPhotoDownload',
	acdPhotoPreview = 'acdPhotoPreview',
}
