export const tags = [
	{ text: 'Loreal', value: 100 },
	{ text: 'ACD', value: 40 },
	{ text: 'Vichy', value: 62 },
	{ text: 'Dercos', value: 40 },
	{ text: 'LRP', value: 77 },
	{ text: 'Skinceuticals', value: 34 },
	{ text: 'сыворотка', value: 10 },
	{ text: 'молекула', value: 10 },
	{ text: 'крем', value: 10 },
	{ text: 'вулканическая вода', value: 10 },
	{ text: 'аминексил', value: 10 },
	{ text: 'liftactiv', value: 16 },
	{ text: 'mireral', value: 33 },
	{ text: 'neovadiol', value: 12 },
	{ text: 'normaderm', value: 14 },
	{ text: 'anthelios', value: 20 },
	{ text: 'baume', value: 14 },
	{ text: 'antiage', value: 12 },
	{ text: 'cicaplast', value: 16 },
	{ text: 'effaclar', value: 18 },
	{ text: 'лосьон', value: 10 },
	{ text: 'serum', value: 15 },
	{ text: 'эксфолиант', value: 8 },
	{ text: 'увлажнение', value: 20 },
	{ text: 'очищение', value: 18 },
	{ text: 'спрей', value: 12 },
	{ text: 'гидратация', value: 15 },
	{ text: 'крем-гель', value: 10 },
	{ text: 'бальзам', value: 14 },
	{ text: 'масло', value: 12 },
	{ text: 'ретинол', value: 17 },
	{ text: 'гиалуроновая кислота', value: 10 },
	{ text: 'витамин С', value: 12 },
	{ text: 'спф', value: 15 },
]
