name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build with Next.js
        run: |
          yarn build
          yarn export
          # Создаем .nojekyll файл
          touch out/.nojekyll
          # Копируем _next в next и обновляем пути
          cd out && cp -r _next next
          find . -name "*.html" -exec sed -i 's/\/_next\//\/next\//g' {} \;
          find . -name "*.js" -exec sed -i 's/\/_next\//\/next\//g' {} \;
          find . -name "*.css" -exec sed -i 's/\/_next\//\/next\//g' {} \;
          # Также обновляем пути для assetPrefix
          find . -name "*.html" -exec sed -i 's/\/react-congress-main\/_next\//\/react-congress-main\/next\//g' {} \;
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4